root: true
extends:
  - '@nuxtjs/eslint-config-typescript'
parser: vue-eslint-parser
parserOptions:
  parser: '@typescript-eslint/parser'
rules:
  vue/singleline-html-element-content-newline: off
  vue/max-attributes-per-line: off
  vue/html-self-closing: off
